spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/wanderwise
    username: postgres
    password: vivek1224@nigam

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: user
      password: pass123

server:
  port: 8080